### ISSUE TITLE
UX-Peer Review

### ISSUE THREAD

**Issue by slaterjen** [chonnens/web-iv-portfolio-site#4]
Overall grade: Proficient 

I think overall the site's user experience makes sense. It's really helpful to have multiple links throughout the website to get back to certain parts of the site. 

There were only a couple hiccups like your sliding images at the bottom of your project page not responding on larger screen sizes. Also, your side menu nav bar covers some of your content at mobile size.

**Comment by SpicyKeeKay** [comment]
Overall:Proficient

**Comment by elladurham** [comment]
Some of your content seems to be outside of the off-canvas wrapper.

<img width="512" alt="screen shot 2015-11-14 at 9 36 41 am" src="https://cloud.githubusercontent.com/assets/2342978/11164341/63c40620-8ab3-11e5-8a03-540c77f81ea4.png">

**Comment by elladurham** [comment]
Consider adding some space between your contact form and your footer so that when I click the "contact link" the browser will scroll us to the top of the contact form or at least the contact form will display more mid-screen. It could read like the nav has taken us to the skills icons.
<img width="734" alt="screen shot 2015-11-14 at 9 39 42 am" src="https://cloud.githubusercontent.com/assets/2342978/11164350/b883254c-8ab3-11e5-8c60-9017ed9eef84.png">
